/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as SidebarIndexRouteImport } from './../routes/_sidebar/index'
import { Route as SidebarTransformerReadingsRouteImport } from './../routes/_sidebar/transformer-readings'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarNasaEquipmentRouteImport } from './../routes/_sidebar/nasa-equipment'
import { Route as SidebarElectricalFaultsRouteImport } from './../routes/_sidebar/electrical-faults'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarIndexRoute = SidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarTransformerReadingsRoute =
  SidebarTransformerReadingsRouteImport.update({
    id: '/transformer-readings',
    path: '/transformer-readings',
    getParentRoute: () => SidebarRouteRoute,
  } as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarNasaEquipmentRoute = SidebarNasaEquipmentRouteImport.update({
  id: '/nasa-equipment',
  path: '/nasa-equipment',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarElectricalFaultsRoute = SidebarElectricalFaultsRouteImport.update({
  id: '/electrical-faults',
  path: '/electrical-faults',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarIndexRoute
  '/electrical-faults': typeof SidebarElectricalFaultsRoute
  '/nasa-equipment': typeof SidebarNasaEquipmentRoute
  '/profile': typeof SidebarProfileRoute
  '/transformer-readings': typeof SidebarTransformerReadingsRoute
}
export interface FileRoutesByTo {
  '/electrical-faults': typeof SidebarElectricalFaultsRoute
  '/nasa-equipment': typeof SidebarNasaEquipmentRoute
  '/profile': typeof SidebarProfileRoute
  '/transformer-readings': typeof SidebarTransformerReadingsRoute
  '/': typeof SidebarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/electrical-faults': typeof SidebarElectricalFaultsRoute
  '/_sidebar/nasa-equipment': typeof SidebarNasaEquipmentRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/transformer-readings': typeof SidebarTransformerReadingsRoute
  '/_sidebar/': typeof SidebarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/electrical-faults'
    | '/nasa-equipment'
    | '/profile'
    | '/transformer-readings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/electrical-faults'
    | '/nasa-equipment'
    | '/profile'
    | '/transformer-readings'
    | '/'
  id:
    | '__root__'
    | '/_sidebar'
    | '/_sidebar/electrical-faults'
    | '/_sidebar/nasa-equipment'
    | '/_sidebar/profile'
    | '/_sidebar/transformer-readings'
    | '/_sidebar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/': {
      id: '/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarIndexRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/transformer-readings': {
      id: '/_sidebar/transformer-readings'
      path: '/transformer-readings'
      fullPath: '/transformer-readings'
      preLoaderRoute: typeof SidebarTransformerReadingsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/nasa-equipment': {
      id: '/_sidebar/nasa-equipment'
      path: '/nasa-equipment'
      fullPath: '/nasa-equipment'
      preLoaderRoute: typeof SidebarNasaEquipmentRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/electrical-faults': {
      id: '/_sidebar/electrical-faults'
      path: '/electrical-faults'
      fullPath: '/electrical-faults'
      preLoaderRoute: typeof SidebarElectricalFaultsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarElectricalFaultsRoute: typeof SidebarElectricalFaultsRoute
  SidebarNasaEquipmentRoute: typeof SidebarNasaEquipmentRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarTransformerReadingsRoute: typeof SidebarTransformerReadingsRoute
  SidebarIndexRoute: typeof SidebarIndexRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarElectricalFaultsRoute: SidebarElectricalFaultsRoute,
  SidebarNasaEquipmentRoute: SidebarNasaEquipmentRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarTransformerReadingsRoute: SidebarTransformerReadingsRoute,
  SidebarIndexRoute: SidebarIndexRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
