"""App metadata - used when not generated by apx build."""

from pathlib import Path

app_name = "agile-ish-v3"
app_entrypoint = "agile_ish_v3.backend.app:app"
app_slug = "agile_ish_v3"
api_prefix = "/api"
dist_dir = Path(__file__).parent / "__dist__"
